### ISSUE TITLE
Error without News Extension

### ISSUE THREAD

**Issue by MrSilaz** [koehlersimon/slug#10]
HINT: When you don't have the News Extension, use this in your configuration....

```
module.tx_slug.settings.additionalTables >
module.tx_slug {
	settings{
		additionalTables{
			tx_ownext_domain_model_newsitem{
				label = Ownext
				slugField = slug
				titleField = title
				icon = EXT:own_ext/Resources/Public/Icons/own_ext.svg
			}
		}
	}
}
```

@koehlersimon please remove news config or check if installed :-) the fluid drop a error because he does find the icon ;-)

**Comment by koehlersimon** [comment]
Thanks for this hint. The news configuration is now inactive. Will push the new version of the extension to the official repository soon with some updates.
