### ISSUE TITLE
Save All on CustomRecords

### ISSUE THREAD

**Issue by MrSilaz** [koehlersimon/slug#11]
Hi,
how can i find the "Save All" Button on CustomRecords ?

**Comment by koehlersimon** [comment]
Should be right next to the "Generate All" button.

**Comment by MrSilaz** [comment]
#now X-D https://github.com/koehlersimon/slug/commit/79bbbef89943e043597619627643c4c1ccf1aa4e#diff-b2836e1b98b6d8c2487cdfd98a5fb187
