### ISSUE TITLE
[Feature Request] CLI integration

### ISSUE THREAD

**Issue by unherz** [koehlersimon/slug#12]
Hey,

It would be pretty cool if you can run this extension from CLI with the same parameters as the be module.
Maybo s.th. like `./vendor/bin/typo3slugs slugs:regenerate` and the aprameters

- uid of the root page
- depth
- languages

**Comment by koehlersimon** [comment]
This feature is currently not planned, but I'll think about it.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
+1

Unfortunately for us this extension is only practicable with CLI integration.
