### ISSUE TITLE
AdditionalTable template is not using defined titleField for displaying list

### ISSUE THREAD

**Issue by alex-boehm** [koehlersimon/slug#15]
By defining additional records to handle in the backend module the list only shows the record titles if they have a 'title' field in the database.
If no title field exists the column is empty for all found records, even if 'titleField' is set correctly.

Setting 'titleField' should be used for the display of records in the list.

Solution:
In file slug/Resources/Private/Templates/AdditionalTable.html:68
Replace:
`<td><strong>{record.title}</strong></td>`
with
`<td><strong>{record.{titleField}}</strong></td>`

**Comment by koehlersimon** [comment]
Thank you very much for this hint and code, I apreciate it! Has been updated now.
