### ISSUE TITLE
Remove Slash from Slug if titlefield has a "/" or "\" in it

### ISSUE THREAD

**Issue by hrdyy** [koehlersimon/slug#16]
Would be nice if there is a Option to Remove Slashes from the title field.

The TCA Config provides this feature. Maybe the process could respect these Option for a Fallback Character.

**Comment by koehlersimon** [comment]
This feature should be implemented here in this class of the TYPO3 core: TYPO3\CMS\Core\DataHandling\SlugHelper. I am using this class for creating the slug. The same happens, when you generate a slug with slash in the page settings. But I will think about a solution until this is fixed.
