### ISSUE TITLE
Class PageController does not exist

### ISSUE THREAD

**Issue by SchmidtWebmedia** [koehlersimon/slug#17]
Hi, 
I have updated the extension "slug" to 2.0.1 and now get the following error in the backend:

Uncaught TYPO3 Exception: #1278450972: Class SIMONKOEHLER\Slug\Controller\PageController does not exist. Reflection failed.

**Comment by koehlersimon** [comment]
Hey, this is because the Namespaces have changed. You only need to clear the main cache and autoload data via the install tool and it should work.

**Comment by SchmidtWebmedia** [comment]
I have already done this several times without success. I had to reinstall the extension to make it work.
