### ISSUE TITLE
use generate() instead of sanitize()

### ISSUE THREAD

**Issue by oliverbeck** [koehlersimon/slug#19]
Hi,

First I would like to thank you for your extension, very good work! I'm using your ext with custom records (tx_news). I've extended the TCA config with a postModifier

`$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['path_segment']['config'] = [
    'type' => 'slug',
    'size' => 50,
    'generatorOptions' => [
        'fields' => ['datetime','title'],
        'fieldSeparator' => '/',
        'replacements' => [
            '/' => '-'
        ],
        'postModifiers' => [
            Intersim\IsDesign\Utility\SlugUtility::class . '->buildSlugWithDatetime',
        ],
    ],
    'fallbackCharacter' => '-',
    'eval' => 'uniqueInSite',
    'default' => ''
];`

In your AjaxController you use the SlugHelper method sanitize() to calculate the record slugs. This method seems to ignore my config. When use the generate() method (like you do above for generating page slugs), it works.

Are there any reasons to use the sanitize() instead of generate()?

**Comment by koehlersimon** [comment]
Hi, sorry for the late reply.

The sanitize function only cleans up, while the generate function e.g. also creates a slash, and is therefore more suitable for pages. See also the descriptions of the functions in the class directly:

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/DataHandling/SlugHelper.php

I would therefore prefer to leave it with sanitize now, but maybe come back to it. Hope your project works anyway!
