### ISSUE TITLE
Duplicate entries for news

### ISSUE THREAD

**Issue by matin73** [koehlersimon/slug#2]
If you have news with same title and run update slugs for news, the uri for news is not unique any more. Default typo3 generates uri part like "/news-title" and "news-title-1" if it is not unique. Extension slug overwrites this entries with "/news-title"  and "/news-title"  - so this causes problems because second one is not unique.

**Comment by koehlersimon** [comment]
Hey, the issue should be fixed now. You can use the current GitHub version or wait a few hours until I have updated the official repository. I still need to do some tests in different systems before. https://github.com/koehlersimon/slug/blob/master/CHANGELOG.md
