### ISSUE TITLE
Custom Records manual improvement

### ISSUE THREAD

**Issue by andwee** [koehlersimon/slug#21]
Hey Simon,

first thank you for the great work! I hope I've missed nothing in the docs, but it took me some time to find out, that I have to activate the "Custom records enabled" checkbox of the extension configuration, to make the whole "CUSTOM RECORDS" part work. Perhaps a little hint in the manual would help other?

Best wishes,
Andy

**Comment by koehlersimon** [comment]
Hey Andy,

thanks a lot for the hint. 
I've added it to the description!

Saludos,
Simon
