### ISSUE TITLE
Allow using slugs if a table doesn't have a field for the slug

### ISSUE THREAD

**Issue by cboltz** [koehlersimon/slug#25]
The documentation says about `custom records`:

    Editing the slugs works only if the desired table contains 
    a field for the title and a field for the slug. 

Would it be possible to get rid of this requirement?

In my case, I use the `cal` extension. I'd like to generate a slug for each event in the calendar, but unfortunately the table doesn't have a field where I can store the path segment.

Alternative question: is there an easy way to add a `path_segment` field to the table? (I guess it could be done with an extension, but unfortunately I don't know anything about writing Typo3 extensions.)

**Comment by koehlersimon** [comment]
I think it' a good practise to use an extra slug field. So I experimented with this and created a little extension as an example: https://github.com/koehlersimon/cal_slug

You should be able to use it. I created it with TYPO3 9.8.5 and the cal extension.
Tested in TYPO3 9.5.8 up to 10.2.2.
Please do database backups before installing, you never know.

The only thing you would have to do is the URL-configuration for the frontend.
Good luck!
