### ISSUE TITLE
Sysfolders should not show up in the page list

### ISSUE THREAD

**Issue by christianbltr** [koehlersimon/slug#3]
Hey and thanks for that extension, great to have the possibility to mass-edit the slugs.

Currently sys folders show up in the the list of pages in the "Slugs" backend module. If you edit the page properties of a sys folder, the slug field cannot be edited. So I think they should not show up in the "Slugs" module.

**Comment by koehlersimon** [comment]
Hey, of course slugs for Folders can be edited in the page properties, at least in my latest 9.5.4 projects. Makes no sense to me as well, but it's like that. I will think about an option to configure something like "don't show sys folders in Slug module".
