### ISSUE TITLE
Add composer.json and register the package in packagist.org

### ISSUE THREAD

**Issue by christianbltr** [koehlersimon/slug#4]
As a developer I would like to find a composer.json in the GitHub repository and the extension should be registered in packagist.org which would make it easier to use composer to install the extension.

**Comment by koehlersimon** [comment]
It will follow. To be honest, I have never worked with composer or packagist.org so far. Just give me a bit time to learn about it...

**Comment by christianbltr** [comment]
If you like a can create a pull request.
