### ISSUE TITLE
Generate slugs for a given page tree

### ISSUE THREAD

**Issue by christianbltr** [koehlersimon/slug#5]
It would be great to have the possibility to generate the slugs for a given page tree from top to bottom, so that a change in the first level is reflected in higher levels.

Currently the list of pages is a flat list. So if you have a tree with for example three levels and the slug of level one changes, this is not reflected directly for sub-pages. You will have to start the "Generate all" and "Save all" functions several times until all levels have been corrected.

**Comment by koehlersimon** [comment]
Thanks for the feedback. Yes I understand what you say and we are already working on different ideas about this. The flat list was the first intention, but there are more things to come for sure. For now I recommend to use the bulk feature only for a filtered result, when you are clear what is going to happen.

**Comment by koehlersimon** [comment]
A feature like this will be available in the next version.
