### ISSUE TITLE
Ajax Fehler im BE

### ISSUE THREAD

**Issue by CarstenHager** [koehlersimon/slug#6]
Hallo Simon,

ich erhalte in meinem System immer einen Ajax Fehler wenn ich eine Aktion in deinem BE-Modul durchführen will.
Hab auch schon mal alle EXT deinstalliert, um sicher zu gehen, dass es nicht durch andere EXT verursacht wird, leider ohne Erfolg.
In einer komplett neuen Installation ging es ohne Probleme.
Hast du einen Idee was hier schief laufen könnte?

Das Log zeigt mir folgenden Fehler an:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function GOCHILLA\Slug\Controller\AjaxController::savePageSlug(), 1 passed and exactly 2 expected | ArgumentCountError thrown in file /html/typo3/typo3conf/ext/slug/Classes/Controller/AjaxController.php in line 32. Requested URL: https://p208591.mittwaldserver.info/typo3/index.php?route=%%2Fajax%%2Fslug%%2Fsave&token=--AnonymizedToken--&uid=1&slug=%%2F`

Sorry, mein Englisch ist nicht so gut, deswegen auf Deutsch.

**Comment by koehlersimon** [comment]
Es hat nun leider aufgrund zu vieler Jobs etwas gedauert, aber diese Fehler sollten mit der neuesten Version, die ich gerade hochgeladen habe, erledigt sein.

**Comment by CarstenHager** [comment]
Danke, klappt jetzt wunderbar!
