### ISSUE TITLE
Missing field 'slug_lock'

### ISSUE THREAD

**Issue by freshworkx** [koehlersimon/slug#8]
Please prevent exception '**Unknown column 'slug_lock' in 'field list'**'. 
Add missing field 'slug_lock' to table 'tx_slug_domain_model_page' or remove it from TCA.

**Comment by koehlersimon** [comment]
Where and when does this message appear? I can not reproduce this error so far.

**Comment by freshworkx** [comment]
This bug was introduced in the initial commit, there was a typo in TCA defintion in Configuration/TCA/tx_slug_domain_model_page.php called "slug_lock" instead of "slug_locked".
But it was fixed with the code cleanup in commit e4cb81d.
Can be closed, thanks.

**Comment by koehlersimon** [comment]
Okay thank you, too
