### ISSUE TITLE
No tags available for this repository

### ISSUE THREAD

**Issue by freshworkx** [koehlersimon/slug#9]
Please tag this repo corresponding to your version in composer.json and register the package in packagist.org. Until now only "dev-master" is available via github.

**Comment by DavidBruchmann** [comment]
Tags for older commits can be assigned this way on command-line:
```
set GIT_COMMITTER_DATE="2019-01-05 05:10" git tag -s v1.0.09
git tag v1.0.09 3b4882d685e4a0e6000285ca9a59e140f16cacd6
git push --tags
```
For the hash it's enough to note the first 7 numbers like this
```
git tag v1.0.09 3b4882d
```
Tags can be also seen in my fork https://github.com/DavidBruchmann/slug

**Comment by pnoreck** [comment]
That would be really nice since we also include all extensions as git sub-module.

**Comment by bernhardberger** [comment]
Yes, please tag your release versions here in the repository. Composer sees the typo3-ter package as abandoned `Package typo3-ter/slug is abandoned, you should avoid using it. Use koehlersimon/slug instead.`, but we can't use version constraints using the suggested `koehlersimon/slug` package on packagist lacks version numbers..

**Comment by koehlersimon** [comment]
I have registered everything here and see lots of downloads. I guess it's working now for all of you? If not, please let me know what else I can do: https://packagist.org/packages/koehlersimon/slug

**Comment by freshworkx** [comment]
@koehlersimon Nope, this is only the half way, so please tag your git repo with coresponding version number from composer.json (e.g. 2.0.0). Recommended @DavidBruchmann post above:
`git tag 2.0.0 3d3b0bb`
`git push --tags`
So other projects can be include your extension by a reliable version constraint and not on your current development dev-master!

**Comment by koehlersimon** [comment]
Like this? https://github.com/koehlersimon/slug/releases

**Comment by freshworkx** [comment]
Yes of course repo looks good now, only packagist seems not up to date at this time.
